In [1]:
import numpy as np

In [2]:
a = np.array([_ for _ in range(12, 24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = np.reshape(a, (12, 1))

In [4]:
b1 = a.reshape(-1, 6)
b2 = a.reshape(-1, 4)
b3 = a.reshape(12, -1)
b4 = a.reshape(6, -1)
b5 = np.reshape(a, (4, -1))

In [6]:
a = np.random.randn(3, 4)
b = a.flatten()
a.size == b.size

True

In [8]:
a = np.arange(20, 0, -2)
b = np.arange(20, 1, -2)
a == b
# Нет разницы


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [11]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
print(v)
v.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

In [12]:
a = np.arange(12)
A = a.reshape(4, 3)
At = np.transpose(A)
B = np.dot(A, At)
print(B.size, B.shape)

# B_inv = np.linalg.inv(B)
# np.linalg.det(B)
# Обратную матрицу B вычислить не получится из-за исключения "Сингулярная
# матрица". Поскольку матрица с определителем 0 имеет не единственное решение.

16 (4, 4)


In [18]:
np.random.seed(42)
c = np.random.randint(0, 16, 16)
C = c.reshape(4, 4)  # (16 ** 0.5, -1)
D = B + C * 10
det_D = np.linalg.det(D)
rank_D = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
B, C, D, D_inv, det_D, rank_D

(array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]), array([[ 6,  3, 12, 14],
        [10,  7, 12,  4],
        [ 6,  9,  2,  6],
        [10, 10,  7,  4]]), array([[ 65,  44, 143, 172],
        [114, 120, 206, 162],
        [ 83, 176, 169, 272],
        [132, 222, 282, 342]]), array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
        [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
        [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
        [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]]), -28511999.999999944, 4)

In [19]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [20]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

In [21]:
a = np.array([[1, 2, 3, 3 , 1],
              [6, 8, 11, 10, 7]]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [22]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

In [24]:
a_centered = a - mean_a
a_centered, a_centered.shape

(array([[-1. , -2.4],
        [ 0. , -0.4],
        [ 1. ,  2.6],
        [ 1. ,  1.6],
        [-1. , -1.4]]), (5, 2))

In [25]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [26]:
N = a_centered.shape[0]
a_cov = a_centered_sp / (N - 1)
a_cov

2.0

In [28]:
cov = np.cov(a.T)[0, 1]
cov

2.0